# Generated by Django 4.2.25 on 2025-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portfolio_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade_level',
            field=models.CharField(choices=[('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('arabic', 'Arabic'), ('social_studies', 'Social Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('computer_science', 'Computer Science'), ('religious_studies', 'Religious Studies')], default='math', max_length=50),
        ),
    ]
