# Generated by Django 4.2.25 on 2025-10-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lesson_grade_level_lesson_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasubmission',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='Detailed AI analysis of student weaknesses: spelling, comprehension, completeness, etc.', null=True),
        ),
    ]
