# Generated by Django 4.2.25 on 2025-10-22 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_qasubmission_ai_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Topic or lesson title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Details about what will be/was taught')),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('arabic', 'Arabic'), ('social_studies', 'Social Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('computer_science', 'Computer Science'), ('religious_studies', 'Religious Studies')], max_length=50)),
                ('grade_level', models.CharField(choices=[('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade')], max_length=2)),
                ('date', models.DateField(help_text='Date when this was/will be taught')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('taught', 'Taught'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Teacher notes about the session')),
                ('completion_notes', models.TextField(blank=True, help_text='Notes after teaching (what went well, issues, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, help_text='Link to existing lesson if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_plans', to='core.lesson')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching Plan',
                'verbose_name_plural': 'Teaching Plans',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'date'], name='core_teachi_teacher_dbf511_idx'), models.Index(fields=['teacher', 'subject'], name='core_teachi_teacher_57e82e_idx')],
            },
        ),
    ]
