# Generated by Django 4.2.25 on 2025-10-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teachingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingplan',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of day for the session', null=True),
        ),
    ]
