# Generated by Django 4.2.25 on 2025-10-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_teachingplan_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingplan',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes after teaching (what went well, challenges, etc.)'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='date',
            field=models.DateField(help_text='Date of the session'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='description',
            field=models.TextField(blank=True, help_text='What will be covered'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Expected duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='grade_level',
            field=models.CharField(choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to an existing lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_plans', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or preparation details'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='title',
            field=models.CharField(help_text='Title/topic of the session', max_length=255),
        ),
    ]
