# Generated by Django 4.2.25 on 2025-10-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_school_cre_school_delegation_school_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_alter_teachingplan_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Brief description of the lesson plan"),
                ),
                ("content", models.TextField(help_text="Full lesson plan content")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("english", "English"),
                            ("arabic", "Arabic"),
                            ("social_studies", "Social Studies"),
                            ("art", "Art"),
                            ("music", "Music"),
                            ("physical_education", "Physical Education"),
                            ("computer_science", "Computer Science"),
                            ("religious_studies", "Religious Studies"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("1", "1st Grade"),
                            ("2", "2nd Grade"),
                            ("3", "3rd Grade"),
                            ("4", "4th Grade"),
                            ("5", "5th Grade"),
                            ("6", "6th Grade"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        blank=True, default=list, help_text="Learning objectives"
                    ),
                ),
                (
                    "materials_needed",
                    models.JSONField(
                        blank=True, default=list, help_text="Required materials"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, help_text="Estimated duration", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for easier search"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this lesson plan is visible in the vault",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured lesson plans appear at the top",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                (
                    "use_count",
                    models.IntegerField(
                        default=0, help_text="Number of times teachers have used this"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["advisor", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_lesson_plans",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VaultComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.vaultlessonplan",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="For threaded comments",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.vaultcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VaultLessonPlanUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Teacher notes about using this lesson plan",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback about the lesson plan"
                    ),
                ),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="core.vaultlessonplan",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "lesson_plan"],
                        name="core_vaultl_teacher_618037_idx",
                    ),
                    models.Index(
                        fields=["lesson_plan", "used_at"],
                        name="core_vaultl_lesson__6ad889_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vaultlessonplan",
            index=models.Index(
                fields=["subject", "grade_level"], name="core_vaultl_subject_2c2ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaultlessonplan",
            index=models.Index(
                fields=["school", "subject"], name="core_vaultl_school__b1d137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaultlessonplan",
            index=models.Index(
                fields=["is_active", "subject"], name="core_vaultl_is_acti_ae8dd9_idx"
            ),
        ),
    ]
