# Generated by Django 4.2.25 on 2025-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_vaultlessonplan_vaultcomment_vaultlessonplanusage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultlessonplan",
            name="grammar",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Grammar points (for language subjects)",
            ),
        ),
        migrations.AddField(
            model_name="vaultlessonplan",
            name="life_skills_and_values",
            field=models.JSONField(
                blank=True, default=list, help_text="Life skills and values covered"
            ),
        ),
        migrations.AddField(
            model_name="vaultlessonplan",
            name="vocabulary",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Vocabulary words/phrases (for language subjects)",
            ),
        ),
    ]
