# Generated by Django 4.2.25 on 2025-10-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_school_cre_school_delegation_school_latitude_and_more"),
        ("core", "0012_vaultlessonplan_grammar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultlessonplan",
            name="ai_generation_prompt",
            field=models.TextField(
                blank=True, help_text="Custom text/prompt provided for AI generation"
            ),
        ),
        migrations.AddField(
            model_name="vaultlessonplan",
            name="source_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Original teacher if this was imported from their lesson",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_vault_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vaultlessonplan",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manually Created"),
                    ("ai_yearly", "AI Generated - Yearly Breakdown"),
                    ("ai_single", "AI Generated - Single Lesson"),
                    ("imported", "Imported from Teacher"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vaultlessonplan",
            name="teacher_guide_file",
            field=models.FileField(
                blank=True,
                help_text="Teacher guide PDF used for AI generation",
                null=True,
                upload_to="vault/teacher_guides/",
            ),
        ),
        migrations.AddField(
            model_name="vaultlessonplan",
            name="yearly_breakdown_file",
            field=models.FileField(
                blank=True,
                help_text="Yearly breakdown PDF input for AI generation",
                null=True,
                upload_to="vault/yearly_breakdowns/",
            ),
        ),
        migrations.AlterField(
            model_name="vaultlessonplan",
            name="subject",
            field=models.CharField(
                choices=[
                    ("math", "Mathematics"),
                    ("science", "Science"),
                    ("english", "English"),
                    ("french", "French"),
                    ("arabic", "Arabic"),
                    ("social_studies", "Social Studies"),
                    ("art", "Art"),
                    ("music", "Music"),
                    ("physical_education", "Physical Education"),
                    ("computer_science", "Computer Science"),
                    ("religious_studies", "Religious Studies"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="YearlyBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("english", "English"),
                            ("french", "French"),
                            ("arabic", "Arabic"),
                            ("social_studies", "Social Studies"),
                            ("art", "Art"),
                            ("music", "Music"),
                            ("physical_education", "Physical Education"),
                            ("computer_science", "Computer Science"),
                            ("religious_studies", "Religious Studies"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("1", "1st Grade"),
                            ("2", "2nd Grade"),
                            ("3", "3rd Grade"),
                            ("4", "4th Grade"),
                            ("5", "5th Grade"),
                            ("6", "6th Grade"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "input_pdf",
                    models.FileField(
                        help_text="PDF containing curriculum/yearly plan",
                        upload_to="vault/yearly_inputs/",
                    ),
                ),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for AI generation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("generated_plans_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["advisor", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_breakdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_breakdowns",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["advisor", "status"],
                        name="core_yearly_advisor_7f8051_idx",
                    ),
                    models.Index(
                        fields=["school", "subject"],
                        name="core_yearly_school__d32208_idx",
                    ),
                ],
            },
        ),
    ]
