# Generated by Django 4.2.25 on 2025-10-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_vaultlessonplan_ai_generation_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="scheduled_date",
            field=models.DateField(
                blank=True,
                help_text="When this lesson is scheduled to be taught",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="vault_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Vault lesson plan this was generated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_lessons",
                to="core.vaultlessonplan",
            ),
        ),
    ]
