# Generated by Django 4.2.25 on 2025-10-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_lesson_scheduled_date_lesson_vault_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the material"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("doc", "Word Document"),
                            ("ppt", "PowerPoint Presentation"),
                            ("image", "Image"),
                            ("video_link", "Video Link"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload file (PDF, DOC, PPT, images, etc.)",
                        null=True,
                        upload_to="vault/materials/%Y/%m/",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="External URL (for videos, websites, etc.)",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "download_count",
                    models.IntegerField(default=0, help_text="Number of downloads"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vault_lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.vaultlessonplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vault_lesson_plan", "material_type"],
                        name="core_vaultm_vault_l_6d1ca3_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="core_vaultm_is_acti_6b10de_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VaultExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the exercise"
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice Questions"),
                            ("qa", "Question & Answer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        help_text="Array of questions with their structure"
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Time limit in minutes (optional)",
                        null=True,
                    ),
                ),
                ("num_questions", models.IntegerField(help_text="Number of questions")),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Times this exercise was used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vault_lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.vaultlessonplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vault_lesson_plan", "exercise_type"],
                        name="core_vaulte_vault_l_1a6dc7_idx",
                    ),
                    models.Index(
                        fields=["is_active", "exercise_type"],
                        name="core_vaulte_is_acti_f0a3d6_idx",
                    ),
                ],
            },
        ),
    ]
