# Generated by Django 4.2.25 on 2025-11-02 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_vaultmaterial_vaultexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this notebook page')),
                ('student_name', models.CharField(help_text='Student writes their name at top of page', max_length=255)),
                ('exercises_done', models.TextField(blank=True, help_text='Exercises/activities the class did that day')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_viewed', models.BooleanField(default=False)),
                ('teacher_comment', models.TextField(blank=True)),
                ('teacher_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.studentnotebook')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['notebook', '-date'], name='core_notebo_noteboo_e6fa9e_idx'), models.Index(fields=['date'], name='core_notebo_date_8c9118_idx')],
                'unique_together': {('notebook', 'date')},
            },
        ),
    ]
