# Generated by Django 4.2.25 on 2025-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentnotebook_notebookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookpage',
            name='exercises_done',
        ),
        migrations.RemoveField(
            model_name='notebookpage',
            name='student_name',
        ),
        migrations.AddField(
            model_name='notebookpage',
            name='exercises_answers',
            field=models.TextField(blank=True, help_text='Student answers to the exercises'),
        ),
        migrations.AddField(
            model_name='notebookpage',
            name='exercises_set_by_teacher',
            field=models.TextField(blank=True, help_text='Exercises/activities assigned by teacher'),
        ),
        migrations.AddField(
            model_name='notebookpage',
            name='lesson_name',
            field=models.CharField(default='Lesson', help_text='Name of the lesson for this page', max_length=255),
            preserve_default=False,
        ),
    ]
