# Generated by Django 4.2.25 on 2025-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_notebookpage_exercises_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookpage',
            name='lesson_name',
            field=models.CharField(blank=True, default='', help_text='Name of the lesson for this page', max_length=255),
        ),
    ]
