# Generated by Django 4.2.25 on 2025-11-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_notebookpage_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookpage',
            name='answer_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partially Correct')], default='pending', help_text='Teacher evaluation of student answers', max_length=20),
        ),
    ]
