# Generated by Django 4.2.25 on 2025-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question_type',
            field=models.CharField(
                max_length=10,
                choices=[('mcq', 'Multiple Choice'), ('qa', 'Question & Answer')],
                default='mcq'
            ),
        ),
    ]
