# Generated by Django 4.2.25 on 2025-11-08 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_add_test_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('difficulty_level', models.CharField(default='medium', max_length=20)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_versions', to='core.test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('base_test', 'student')},
            },
        ),
    ]
