# Generated by Django 5.2.8 on 2025-11-11 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_personalized_tests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CNPTeacherGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the teacher guide", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of contents and purpose"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("english", "English"),
                            ("arabic", "Arabic"),
                            ("french", "French"),
                            ("social_studies", "Social Studies"),
                            ("islamic_education", "Islamic Education"),
                            ("history", "History"),
                            ("geography", "Geography"),
                            ("civics", "Civics"),
                            ("technology", "Technology"),
                            ("computer_science", "Computer Science"),
                            ("art", "Art"),
                            ("music", "Music"),
                            ("physical_education", "Physical Education"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("grade_1", "1st Grade"),
                            ("grade_2", "2nd Grade"),
                            ("grade_3", "3rd Grade"),
                            ("grade_4", "4th Grade"),
                            ("grade_5", "5th Grade"),
                            ("grade_6", "6th Grade"),
                            ("grade_7", "7th Grade"),
                            ("grade_8", "8th Grade"),
                            ("grade_9", "9th Grade"),
                            ("grade_10", "10th Grade"),
                            ("grade_11", "11th Grade"),
                            ("grade_12", "12th Grade"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "guide_type",
                    models.CharField(
                        choices=[
                            ("yearly", "Yearly Program/Curriculum"),
                            ("unit", "Unit/Chapter Guide"),
                            ("lesson", "Single Lesson Guide"),
                            ("assessment", "Assessment/Evaluation Guide"),
                            ("resource", "Additional Resources"),
                        ],
                        default="lesson",
                        max_length=20,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2024-2025", help_text="e.g., 2024-2025", max_length=20
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="Teacher guide PDF file",
                        upload_to="cnp/teacher_guides/%Y/%m/",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, help_text="Number of pages in PDF", null=True
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Keywords/tags for searchability: ["fractions", "geometry", etc.]',
                    ),
                ),
                (
                    "topics_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of topics covered in this guide",
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Learning objectives from the guide",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times used for lesson generation",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "cnp_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from CNP agent"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Admin review notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "cnp"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cnp_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "cnp"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnp_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CNP Teacher Guide",
                "verbose_name_plural": "CNP Teacher Guides",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "grade_level"],
                        name="core_cnptea_subject_b4877e_idx",
                    ),
                    models.Index(
                        fields=["guide_type", "status"],
                        name="core_cnptea_guide_t_98f233_idx",
                    ),
                    models.Index(
                        fields=["academic_year", "subject"],
                        name="core_cnptea_academi_c4fa78_idx",
                    ),
                ],
            },
        ),
    ]
