# Generated by Django 5.2.8 on 2025-11-17 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_teachertimetable"),
        ("core", "0024_cnpteacherguide"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Arabic Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Region code (e.g., TUN-01)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        blank=True, help_text="Parent governorate", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InspectionVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("visit_time", models.TimeField()),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("class_visit", "Classroom Observation"),
                            ("follow_up", "Follow-up Visit"),
                            ("complaint_based", "Complaint Investigation"),
                            ("evaluation_renewal", "Evaluation Renewal"),
                            ("routine", "Routine Inspection"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=90, help_text="Expected duration in minutes"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Pre-visit notes and preparation"
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_visits",
                        to="accounts.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Visit",
                "verbose_name_plural": "Inspection Visits",
                "ordering": ["-visit_date", "-visit_time"],
            },
        ),
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(help_text="Overall visit summary")),
                (
                    "classroom_observations",
                    models.TextField(
                        blank=True, help_text="Detailed classroom observation notes"
                    ),
                ),
                (
                    "pedagogical_evaluation",
                    models.TextField(
                        blank=True,
                        help_text="Assessment of teaching methods and effectiveness",
                    ),
                ),
                (
                    "teacher_strengths",
                    models.TextField(blank=True, help_text="Identified strengths"),
                ),
                (
                    "improvement_points",
                    models.TextField(blank=True, help_text="Areas for improvement"),
                ),
                (
                    "student_engagement",
                    models.TextField(
                        blank=True, help_text="Student participation and engagement"
                    ),
                ),
                (
                    "material_quality",
                    models.TextField(
                        blank=True, help_text="Quality of teaching materials"
                    ),
                ),
                (
                    "final_rating",
                    models.IntegerField(
                        help_text="Overall rating from 1 (Poor) to 5 (Excellent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Specific recommendations for improvement"
                    ),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="File paths to uploaded documents",
                    ),
                ),
                (
                    "gpi_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_needed", "Revision Needed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gpi_feedback", models.TextField(blank=True)),
                ("gpi_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gpi_reviewer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "gpi"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="core.inspectionvisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Report",
                "verbose_name_plural": "Inspection Reports",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of the month being reported"),
                ),
                ("total_visits", models.IntegerField(default=0)),
                ("completed_visits", models.IntegerField(default=0)),
                ("cancelled_visits", models.IntegerField(default=0)),
                ("pending_visits", models.IntegerField(default=0)),
                (
                    "rating_distribution",
                    models.JSONField(
                        default=dict,
                        help_text="Distribution of ratings given: {1: 2, 2: 5, 3: 10, 4: 8, 5: 3}",
                    ),
                ),
                (
                    "recurring_issues",
                    models.TextField(
                        blank=True,
                        help_text="Common problems identified across multiple visits",
                    ),
                ),
                (
                    "positive_trends",
                    models.TextField(
                        blank=True,
                        help_text="Positive developments and improvements observed",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for regional improvement"
                    ),
                ),
                (
                    "challenges_faced",
                    models.TextField(
                        blank=True,
                        help_text="Challenges encountered during inspections",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("revision_needed", "Revision Needed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("gpi_feedback", models.TextField(blank=True)),
                ("gpi_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gpi_reviewer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "gpi"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_monthly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Report",
                "verbose_name_plural": "Monthly Reports",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="InspectorRegionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["gpi", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_inspectors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspector_assignments",
                        to="core.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspector Region Assignment",
                "verbose_name_plural": "Inspector Region Assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Behavior, Attendance, Teaching Quality",
                        max_length=50,
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True, help_text="Any supporting evidence or documentation"
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("filed_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_inspector",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "inspector"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Complaint",
                "verbose_name_plural": "Teacher Complaints",
                "ordering": ["-filed_at"],
            },
        ),
        migrations.AddField(
            model_name="inspectionvisit",
            name="related_complaint",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a complaint-based inspection",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_visits",
                to="core.teachercomplaint",
            ),
        ),
        migrations.CreateModel(
            name="TeacherRatingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspection_type", models.CharField(max_length=30)),
                ("subject_taught", models.CharField(blank=True, max_length=50)),
                ("grade_level", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_record",
                        to="core.inspectionreport",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Rating History",
                "verbose_name_plural": "Teacher Rating Histories",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["inspector", "submitted_at"],
                name="core_inspec_inspect_3fb22e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["teacher", "submitted_at"],
                name="core_inspec_teacher_d88bdf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["gpi_status"], name="core_inspec_gpi_sta_f2406a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["inspector", "month"], name="core_monthl_inspect_763aa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(fields=["status"], name="core_monthl_status_d9bdce_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyreport",
            unique_together={("inspector", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="inspectorregionassignment",
            unique_together={("inspector", "region")},
        ),
        migrations.AddIndex(
            model_name="inspectionvisit",
            index=models.Index(
                fields=["inspector", "visit_date"],
                name="core_inspec_inspect_9fa771_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionvisit",
            index=models.Index(
                fields=["teacher", "visit_date"], name="core_inspec_teacher_81219b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionvisit",
            index=models.Index(fields=["status"], name="core_inspec_status_591e37_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherratinghistory",
            index=models.Index(
                fields=["teacher", "inspection_date"],
                name="core_teache_teacher_2ae2b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherratinghistory",
            index=models.Index(fields=["rating"], name="core_teache_rating_c70dc7_idx"),
        ),
    ]
