# Generated by Django 5.2.8 on 2025-11-17 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_region_inspectionvisit_inspectionreport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionreport",
            name="final_rating",
            field=models.FloatField(
                help_text="Overall rating from 1 (Poor) to 5 (Excellent)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
