# Generated by Django 4.2.25 on 2025-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text='Teacher subjects (1-3 subjects)'),
        ),
    ]
