# Generated by Django 4.2.25 on 2025-10-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_chatmessage_file_attachment_chatmessage_is_edited_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentTeacherChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("english", "English"),
                            ("arabic", "Arabic"),
                            ("social_studies", "Social Studies"),
                            ("art", "Art"),
                            ("music", "Music"),
                            ("physical_education", "Physical Education"),
                            ("computer_science", "Computer Science"),
                            ("religious_studies", "Religious Studies"),
                        ],
                        help_text="Optional: specific subject being discussed",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_teacher_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student this chat is about",
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_teacher_chats_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_parent_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Teacher Chat",
                "verbose_name_plural": "Parent-Teacher Chats",
                "ordering": ["-updated_at"],
                "unique_together": {("parent", "teacher", "student")},
            },
        ),
        migrations.CreateModel(
            name="ParentTeacherMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="parent_teacher_attachments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.parentteacherchat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pt_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Teacher Message",
                "verbose_name_plural": "Parent-Teacher Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentStudentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("relative", "Relative"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary parent/guardian"
                    ),
                ),
                ("can_view_grades", models.BooleanField(default=True)),
                ("can_chat_teachers", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the relationship"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Student Relationship",
                "verbose_name_plural": "Parent-Student Relationships",
                "ordering": ["-is_primary", "-created_at"],
                "unique_together": {("parent", "student")},
            },
        ),
    ]
