# Generated by Django 4.2.25 on 2025-10-22 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_parentteacherchat_parentteachermessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('arabic', 'Arabic'), ('social_studies', 'Social Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('computer_science', 'Computer Science'), ('religious_studies', 'Religious Studies')], max_length=50)),
                ('grade_level', models.CharField(choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], max_length=20)),
                ('current_chapter', models.CharField(help_text='Current chapter/unit being taught', max_length=255)),
                ('chapter_number', models.IntegerField(default=1, help_text='Chapter number in curriculum')),
                ('total_chapters', models.IntegerField(default=10, help_text='Total chapters in curriculum')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Progress',
                'verbose_name_plural': 'Teacher Progress Records',
                'ordering': ['-updated_at'],
                'unique_together': {('teacher', 'subject', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons_created', models.IntegerField(default=0)),
                ('total_mcq_tests_created', models.IntegerField(default=0)),
                ('total_qa_tests_created', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('average_student_score', models.FloatField(default=0.0, help_text='Average score across all students')),
                ('average_student_rating', models.FloatField(default=0.0, help_text='Average rating from students (1-5)')),
                ('total_student_ratings', models.IntegerField(default=0)),
                ('average_advisor_rating', models.FloatField(default=0.0, help_text='Average rating from advisors (1-5)')),
                ('total_advisor_ratings', models.IntegerField(default=0)),
                ('overall_rating', models.FloatField(default=0.0, help_text='Weighted average rating')),
                ('last_lesson_created', models.DateTimeField(blank=True, null=True)),
                ('last_test_created', models.DateTimeField(blank=True, null=True)),
                ('subjects_taught', models.JSONField(default=list, help_text='List of subjects taught')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Analytics',
                'verbose_name_plural': 'Teacher Analytics',
            },
        ),
        migrations.CreateModel(
            name='ChapterProgressNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_chapter', models.CharField(max_length=255)),
                ('previous_chapter_number', models.IntegerField()),
                ('new_chapter', models.CharField(max_length=255)),
                ('new_chapter_number', models.IntegerField()),
                ('ai_detected', models.BooleanField(default=True, help_text='Whether this was detected by AI')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence score (0-1)')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed by Advisor'), ('rejected', 'Rejected - Revert to Previous')], default='pending', max_length=20)),
                ('advisor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(limit_choices_to={'role': 'advisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_notifications', to=settings.AUTH_USER_MODEL)),
                ('teacher_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.teacherprogress')),
            ],
            options={
                'verbose_name': 'Chapter Progress Notification',
                'verbose_name_plural': 'Chapter Progress Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
