# Generated by Django 4.2.25 on 2025-10-23 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teacherprogress_teacheranalytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
