# Generated by Django 5.2.8 on 2025-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_role_teachergradeassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("admin", "Administrator"),
                    ("advisor", "Advisor"),
                    ("director", "School Director"),
                    ("cnp", "CNP Agent"),
                ],
                max_length=10,
            ),
        ),
    ]
