# Generated by Django 5.2.8 on 2025-11-11 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('admin', 'Administrator'), ('advisor', 'Advisor'), ('director', 'School Director'), ('cnp', 'CNP Agent'), ('mandobiya', 'Inspector/Advisor (Mandobiya)')], max_length=10),
        ),
        migrations.CreateModel(
            name='MandobiyaDashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_teachers_assigned', models.IntegerField(default=0)),
                ('teachers_needing_attention', models.IntegerField(default=0)),
                ('total_inspections_conducted', models.IntegerField(default=0)),
                ('inspections_this_month', models.IntegerField(default=0)),
                ('pending_inspections', models.IntegerField(default=0)),
                ('average_teacher_score', models.FloatField(default=0.0)),
                ('teachers_improving', models.IntegerField(default=0)),
                ('teachers_declining', models.IntegerField(default=0)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('pending_reviews', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandobiya', models.OneToOneField(limit_choices_to={'role': 'mandobiya'}, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandobiya Dashboard Stats',
                'verbose_name_plural': 'Mandobiya Dashboard Stats',
            },
        ),
        migrations.CreateModel(
            name='MandobiyaTeacherMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inspections', models.IntegerField(default=0)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('average_inspection_score', models.FloatField(default=0.0, help_text='Average overall score from all inspections')),
                ('improvement_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('new', 'New - Insufficient Data')], default='new', max_length=20)),
                ('common_strengths', models.JSONField(default=list, help_text='Most frequently noted strengths')),
                ('common_weaknesses', models.JSONField(default=list, help_text='Most frequently noted weaknesses')),
                ('average_student_score', models.FloatField(default=0.0, help_text='Average student test scores')),
                ('student_count', models.IntegerField(default=0)),
                ('completed_action_items', models.IntegerField(default=0)),
                ('pending_action_items', models.IntegerField(default=0)),
                ('latest_review_score', models.FloatField(blank=True, null=True)),
                ('latest_review_date', models.DateField(blank=True, null=True)),
                ('needs_attention', models.BooleanField(default=False, help_text='Flagged for immediate attention')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='mandobiya_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandobiya Teacher Metrics',
                'verbose_name_plural': 'Mandobiya Teacher Metrics',
            },
        ),
        migrations.CreateModel(
            name='TeacherInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('arabic', 'Arabic'), ('social_studies', 'Social Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('computer_science', 'Computer Science'), ('religious_studies', 'Religious Studies')], max_length=50)),
                ('scheduled_date', models.DateField(help_text='Date of the inspection')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Time of the inspection', null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Expected duration in minutes')),
                ('purpose', models.TextField(help_text='Purpose and objectives of this inspection')),
                ('pre_inspection_notes', models.TextField(blank=True, help_text='Notes before the inspection')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('mandobiya', models.ForeignKey(limit_choices_to={'role': 'mandobiya'}, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='accounts.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Inspection',
                'verbose_name_plural': 'Teacher Inspections',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Quality of teaching delivery (1-5)')),
                ('lesson_planning', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Lesson planning and organization (1-5)')),
                ('student_engagement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Student engagement level (1-5)')),
                ('classroom_management', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Classroom management skills (1-5)')),
                ('content_knowledge', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Subject matter expertise (1-5)')),
                ('use_of_resources', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Effective use of teaching resources (1-5)')),
                ('overall_score', models.FloatField(editable=False, help_text='Average of all ratings')),
                ('strengths', models.TextField(help_text='Observed strengths and positive aspects')),
                ('areas_for_improvement', models.TextField(help_text='Areas that need improvement')),
                ('specific_observations', models.TextField(help_text='Specific observations during the inspection')),
                ('recommendations', models.TextField(help_text='Recommendations for professional development')),
                ('action_items', models.JSONField(default=list, help_text='List of action items: [{item: str, deadline: date, completed: bool}]')),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('evidence_photos', models.JSONField(blank=True, default=list, help_text='URLs to evidence photos from the inspection')),
                ('lesson_materials_reviewed', models.TextField(blank=True, help_text='Notes on reviewed lesson materials')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_acknowledged', models.BooleanField(default=False)),
                ('teacher_comments', models.TextField(blank=True, help_text='Teacher response to the review')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.teacherinspection')),
            ],
            options={
                'verbose_name': 'Inspection Review',
                'verbose_name_plural': 'Inspection Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherinspection',
            index=models.Index(fields=['mandobiya', 'status'], name='accounts_te_mandobi_e6fb83_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinspection',
            index=models.Index(fields=['teacher', 'status'], name='accounts_te_teacher_f02f52_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinspection',
            index=models.Index(fields=['school', 'scheduled_date'], name='accounts_te_school__7ebeee_idx'),
        ),
    ]
