# Generated by Django 5.2.8 on 2025-11-11 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role_mandobiyadashboardstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAdvisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('arabic', 'Arabic'), ('social_studies', 'Social Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('computer_science', 'Computer Science'), ('religious_studies', 'Religious Studies')], help_text='Subject for this assignment', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Assignment notes or instructions')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(limit_choices_to={'role': 'advisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'mandobiya'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_advisor_assignments', to='accounts.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher-Advisor Assignment',
                'verbose_name_plural': 'Teacher-Advisor Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='accounts_te_teacher_551de6_idx'), models.Index(fields=['advisor', 'is_active'], name='accounts_te_advisor_9ff879_idx'), models.Index(fields=['school', 'subject'], name='accounts_te_school__c04343_idx')],
                'unique_together': {('teacher', 'advisor', 'subject')},
            },
        ),
    ]
