# Generated by Django 5.2.8 on 2025-11-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacheradvisorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinspection',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Advisor assigned to conduct the inspection', limit_choices_to={'role': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL),
        ),
    ]
