# Generated by Django 5.2.8 on 2025-11-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_teacherinspection_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('inspection_scheduled', 'Inspection Scheduled'), ('inspection_started', 'Inspection Started'), ('inspection_completed', 'Inspection Completed'), ('inspection_cancelled', 'Inspection Cancelled'), ('review_submitted', 'Review Submitted'), ('advisor_assigned', 'Advisor Assigned to Teacher'), ('message_received', 'Message Received'), ('test_submitted', 'Test Submitted'), ('test_reviewed', 'Test Reviewed'), ('general', 'General Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, help_text='e.g., inspection, review, test', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'), models.Index(fields=['recipient', 'created_at'], name='accounts_no_recipie_59193a_idx')],
            },
        ),
    ]
