# Generated by Django 5.2.8 on 2025-11-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinspection',
            name='advisor_completed_at',
            field=models.DateTimeField(blank=True, help_text='When advisor reported completing inspection', null=True),
        ),
        migrations.AddField(
            model_name='teacherinspection',
            name='advisor_notes',
            field=models.TextField(blank=True, help_text='Notes from advisor about the inspection'),
        ),
        migrations.AddField(
            model_name='teacherinspection',
            name='advisor_started_at',
            field=models.DateTimeField(blank=True, help_text='When advisor reported starting inspection', null=True),
        ),
        migrations.AddField(
            model_name='teacherinspection',
            name='completion_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinspection',
            name='completion_verified_by_mandobiya',
            field=models.BooleanField(default=False, help_text='Whether Mandobiya verified completion'),
        ),
        migrations.AddField(
            model_name='teacherinspection',
            name='start_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinspection',
            name='start_verified_by_mandobiya',
            field=models.BooleanField(default=False, help_text='Whether Mandobiya verified the start'),
        ),
    ]
