# Generated by Django 5.2.8 on 2025-11-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_old_mandobiya_choice'),
        ('core', '0024_cnpteacherguide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegationdashboardstats',
            options={'verbose_name': 'Delegation Dashboard Stats', 'verbose_name_plural': 'Delegation Dashboard Stats'},
        ),
        migrations.AlterModelOptions(
            name='delegationteachermetrics',
            options={'verbose_name': 'Delegation Teacher Metrics', 'verbose_name_plural': 'Delegation Teacher Metrics'},
        ),
        migrations.AlterField(
            model_name='delegationteachermetrics',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='delegation_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherinspection',
            name='completion_verified_by_delegator',
            field=models.BooleanField(default=False, help_text='Whether Delegator verified completion'),
        ),
        migrations.AlterField(
            model_name='teacherinspection',
            name='start_verified_by_delegator',
            field=models.BooleanField(default=False, help_text='Whether Delegator verified the start'),
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('planned_absence', 'Planned Absence')], default='absent', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, help_text='Time teacher marked present', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Time teacher marked departure', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for absence (sick leave, training, etc.)')),
                ('is_planned', models.BooleanField(default=False, help_text='Was this absence reported in advance?')),
                ('planned_at', models.DateTimeField(blank=True, help_text='When the absence was reported', null=True)),
                ('verified_by_delegator', models.BooleanField(default=False)),
                ('verified_by_advisor', models.BooleanField(default=False)),
                ('delegator_notes', models.TextField(blank=True)),
                ('advisor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to=settings.AUTH_USER_MODEL)),
                ('teaching_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.teachingplan')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence')], default='absent', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='When attendance was marked')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='students_marked_by_teacher', to=settings.AUTH_USER_MODEL)),
                ('teacher_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_records', to='accounts.teacherattendance')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ['-date', 'student__username'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('excused_days', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0, help_text='Percentage of present days')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-month', 'user__username'],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['teacher', 'date'], name='accounts_te_teacher_452db2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date', 'status'], name='accounts_te_date_378656_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date')},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='accounts_st_student_352ead_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['teacher', 'date'], name='accounts_st_teacher_4c26d8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'], name='accounts_st_date_e3a1bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'teacher', 'date')},
        ),
    ]
