# Generated by Django 5.2.8 on 2025-11-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_attendance_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('admin', 'Administrator'), ('advisor', 'Advisor'), ('director', 'School Director'), ('cnp', 'CNP Agent'), ('delegation', 'Inspector/Advisor (Delegation)'), ('gdhr', 'GDHR (Human Resources)'), ('minister', 'Minister')], max_length=10),
        ),
    ]
