# Generated by Django 5.2.8 on 2025-11-12 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Expected check-in time')),
                ('end_time', models.TimeField(help_text='Expected check-out time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['teacher', 'day_of_week'], name='accounts_te_teacher_0ce105_idx'), models.Index(fields=['is_active'], name='accounts_te_is_acti_0635d7_idx')],
                'unique_together': {('teacher', 'day_of_week')},
            },
        ),
    ]
