# Generated by Django 5.2.8 on 2025-11-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_teachertimetable"),
        ("core", "0025_region_inspectionvisit_inspectionreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic region for inspection purposes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="core.region",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("admin", "Administrator"),
                    ("advisor", "Advisor"),
                    ("director", "School Director"),
                    ("cnp", "CNP Agent"),
                    ("inspector", "Inspector"),
                    ("gpi", "GPI (General Pedagogical Inspectorate)"),
                    ("delegation", "Inspector/Advisor (Delegation)"),
                    ("gdhr", "GDHR (Human Resources)"),
                    ("minister", "Minister"),
                ],
                max_length=10,
            ),
        ),
    ]
