# Generated by Django 5.2.8 on 2025-11-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_school_region_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('admin', 'Administrator'), ('advisor', 'Advisor'), ('director', 'School Director'), ('cnp', 'CNP Agent'), ('inspector', 'Inspector'), ('gpi', 'GPI (General Pedagogical Inspectorate)'), ('delegation', 'Inspector/Advisor (Delegation)'), ('gdhr', 'GDHR (Human Resources)'), ('minister', 'Minister'), ('secretary', 'General Secretary')], max_length=10),
        ),
    ]
