# Generated by Django 5.2.8 on 2025-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_delegation',
            field=models.CharField(blank=True, help_text='Assigned delegation for delegator role', max_length=100, null=True),
        ),
    ]
