# Generated by Django 4.2.26 on 2025-11-20 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_task_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-meeting_date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='followup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('followup_pending', 'Follow-up Pending')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings for flexible categorization'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('document_type', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=150)),
                ('stage', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('waiting_signature', 'Waiting Signature'), ('archived', 'Archived')], default='received', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=150)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('in_implementation', 'In Implementation'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
