# Generated by Django 5.2.8 on 2025-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_assigned_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_region',
            field=models.CharField(blank=True, help_text='Assigned region for inspector/GPI role', max_length=100, null=True),
        ),
    ]
