# Generated by Django 5.2.8 on 2025-11-19 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_assigned_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('region', 'Regional Assignment (Primary Schools)'), ('subject', 'Subject Assignment (Middle/Secondary Schools)')], help_text='Type of assignment: by region or by subject', max_length=10)),
                ('assigned_region', models.CharField(blank=True, help_text='Region/District (CRE) for primary schools (e.g., Tunis 1, Sfax 1)', max_length=100, null=True)),
                ('assigned_subject', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('arabic', 'Arabic'), ('social_studies', 'Social Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('computer_science', 'Computer Science'), ('religious_studies', 'Religious Studies')], help_text='Subject for middle/secondary schools', max_length=50, null=True)),
                ('school_level', models.CharField(choices=[('primary', 'Primary (E.PRIMAIRE)'), ('middle', 'Middle (E.PREP, E.PREP.TECH)'), ('secondary', 'Secondary (LYCEE)')], help_text='School level this assignment applies to', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this assignment')),
                ('assigned_by', models.ForeignKey(help_text='Minister or secretary who made the assignment', limit_choices_to={'role__in': ['minister', 'secretary']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(help_text='Inspector being assigned', limit_choices_to={'role': 'inspector'}, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspector Assignment',
                'verbose_name_plural': 'Inspector Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('inspector', 'assignment_type', 'assigned_region', 'school_level', 'is_active'), ('inspector', 'assignment_type', 'assigned_subject', 'school_level', 'is_active')},
            },
        ),
    ]
