# Generated by Django 5.2.8 on 2025-12-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_meeting_options_alter_task_options_and_more'),
        ('accounts', '0028_inspectorassignment'),
    ]

    operations = [
    ]
